-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE = "INTACT MALE" OR I.SEX_UPON_INTAKE = "INTACT FEMALE")
AND (O.SEX_UPON_OUTCOME = "SPAYED FEMALE" OR O.SEX_UPON_OUTCOME = "Neutered Male")
ORDER BY I.ANIMAL_ID
ASC